# Generated by Django 6.0.7 on 2026-08-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('interview', 'собеседование'), ('company_meeting', 'корпоративная встреча'), ('company_event', 'корпоративное мероприятие'), ('employee_birthday', 'день рождения сотрудника')], default='company_meeting', max_length=50, verbose_name='Тип события')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Название')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Начало встречи')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Конец встречи')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.hirecard', verbose_name='Претендент на должность')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeecard', verbose_name='Сотрудник компании')),
            ],
            options={
                'verbose_name': 'Событие HR',
                'verbose_name_plural': 'События HR',
            },
        ),
    ]
