# Generated by Django 6.0.7 on 2026-08-21 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_hirecard_status'),
        ('employees', '0002_rename_employee_department_employeecard_department_and_more'),
        ('hrcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcalendar',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to='candidates.hirecard', verbose_name='Претендент на должность'),
        ),
        migrations.AlterField(
            model_name='hrcalendar',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hrcalendar',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='employees.employeecard', verbose_name='Сотрудник компании'),
        ),
    ]
