# Generated by Django 6.0.7 on 2026-08-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=200, null=True, verbose_name='Отчество')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='person_photos', verbose_name='Фотография')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('archived_at', models.DateField(blank=True, null=True)),
                ('employee_position', models.CharField(max_length=200, verbose_name='Позиция')),
                ('employee_department', models.CharField(max_length=200, verbose_name='Отдел')),
                ('employee_start_date', models.DateField(verbose_name='Дата начала работы')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
