# Generated by Django 6.0.7 on 2026-08-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecard',
            old_name='employee_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employeecard',
            old_name='employee_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='employeecard',
            old_name='employee_start_date',
            new_name='start_date',
        ),
    ]
