# Generated by Django 6.0.7 on 2026-08-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirecard',
            name='status',
            field=models.CharField(choices=[('contact', 'связались'), ('interview', 'собеседование'), ('offer', 'приглашение на работу'), ('declined', 'отказ')], default='contact', max_length=50, verbose_name='Статус'),
        ),
    ]
