# Generated by Django 6.0.7 on 2026-08-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=200, null=True, verbose_name='Отчество')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='person_photos', verbose_name='Фотография')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('archived_at', models.DateField(blank=True, null=True)),
                ('employee_position', models.CharField(max_length=200, verbose_name='Позиция')),
                ('employee_department', models.CharField(max_length=200, verbose_name='Отдел')),
                ('employee_start_date', models.DateField(verbose_name='Дата начала работы')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='HireCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=200, null=True, verbose_name='Отчество')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='person_photos', verbose_name='Фотография')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('archived_at', models.DateField(blank=True, null=True)),
                ('desired_position', models.CharField(max_length=250, verbose_name='Желаемая позиция')),
                ('resume_link', models.URLField(verbose_name='Резюме')),
                ('interview_date', models.DateTimeField(blank=True, null=True, verbose_name='Время собеседования')),
                ('status', models.CharField(choices=[('contact', 'связались'), ('interview', 'собеседование'), ('offer', 'приглашение на работу'), ('decline', 'отказ')], default='contact', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
            },
        ),
        migrations.CreateModel(
            name='HRCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('interview', 'собеседование'), ('company_meeting', 'корпоративная встреча'), ('company_event', 'корпоративное мероприятие'), ('employee_birthday', 'день рождения сотрудника')], default='company_meeting', max_length=50, verbose_name='Тип события')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Название')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Начало встречи')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Конец встречи')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRMSystem.hirecard')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRMSystem.employeecard')),
            ],
            options={
                'verbose_name': 'Событие HR',
                'verbose_name_plural': 'События HR',
            },
        ),
    ]
