# Generated by Django 6.0.7 on 2026-08-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrcalendar',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='hrcalendar',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='EmployeeCard',
        ),
        migrations.DeleteModel(
            name='HireCard',
        ),
        migrations.DeleteModel(
            name='HRCalendar',
        ),
    ]
